### ISSUE TITLE
Develop with Warnings On

### ISSUE THREAD

**Issue by jeff-at-livecanvas** [merlinscholz/ssgpress#1]
Hi Merlin,
I am following with interest your idea as I believe the WP static world does still have lots of room for new opportunities.

Unfortunately after installing your plugin I am getting just errors and signs that it's still very very young - I'm not getting any result with it.

One thing I would like to tell you is that upon activation a couple notices are printed:

Notice: register_uninstall_hook was called incorrectly. Only a static class method or function can be used in an uninstall hook. Please see Debugging in WordPress for more information. (This message was added in version 3.1.0.) in /Applications/MAMP/htdocs/livecanvas-wp/wp-includes/functions.php on line 5311

I would definitely recommend you to turn WP_DEBUG on in your wp-config file while developing. It's really useful.

Wishing you all the best!

**Comment by merlinscholz** [comment]
Thank you for your input! I just fixed the incorrectly called uninstall hook. Sadly, due to the current situation of the world, I haven't gotten around to working on this side project for a while, but I hope to continue it soon.
